<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlumniSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('alumni')->insert([
            [
                'nim' => '20230001',
                'nama_alumni' => 'Sufyan',
                'prodi' => 'Teknik Informatika',
                'no_hp' => '081234567890',
                'email' => 'sufyan@example.com',
                'tahun_masuk' => 2023,
                'tgl_lulus' => '2027-06-15',
                'tahun_lulus' => 2027,
                'tanggal_kerja_pertama' => null,
                'masa_tunggu' => null,
                'tanggal_mulai_instansi' => null,
                'jenis_instansi' => null,
                'nama_instansi' => null,
                'skala_instansi' => null,
                'lokasi_instansi' => null,
                'kategori_profesi' => null,
                'profesi' => null,
                'nama_atasan' => null,
                'jabatan_atasan' => null,
                'no_hp_atasan' => null,
                'email_atasan' => null,
            ],
            [
                'nim' => '20230002',
                'nama_alumni' => 'Renald',
                'prodi' => 'Sistem Informasi',
                'no_hp' => '081234567891',
                'email' => 'renald@example.com',
                'tahun_masuk' => 2023,
                'tgl_lulus' => '2027-06-15',
                'tahun_lulus' => 2027,
                'tanggal_kerja_pertama' => null,
                'masa_tunggu' => null,
                'tanggal_mulai_instansi' => null,
                'jenis_instansi' => null,
                'nama_instansi' => null,
                'skala_instansi' => null,
                'lokasi_instansi' => null,
                'kategori_profesi' => null,
                'profesi' => null,
                'nama_atasan' => null,
                'jabatan_atasan' => null,
                'no_hp_atasan' => null,
                'email_atasan' => null,
            ],
            [
                'nim' => '20230003',
                'nama_alumni' => 'Daffa',
                'prodi' => 'Teknik Elektro',
                'no_hp' => '081234567892',
                'email' => 'daffa@example.com',
                'tahun_masuk' => 2023,
                'tgl_lulus' => '2027-06-15',
                'tahun_lulus' => 2027,
                'tanggal_kerja_pertama' => null,
                'masa_tunggu' => null,
                'tanggal_mulai_instansi' => null,
                'jenis_instansi' => null,
                'nama_instansi' => null,
                'skala_instansi' => null,
                'lokasi_instansi' => null,
                'kategori_profesi' => null,
                'profesi' => null,
                'nama_atasan' => null,
                'jabatan_atasan' => null,
                'no_hp_atasan' => null,
                'email_atasan' => null,
            ],
            [
                'nim' => '20230004',
                'nama_alumni' => 'Maharani',
                'prodi' => 'Manajemen',
                'no_hp' => '081234567893',
                'email' => 'maharani@example.com',
                'tahun_masuk' => 2023,
                'tgl_lulus' => '2027-06-15',
                'tahun_lulus' => 2027,
                'tanggal_kerja_pertama' => null,
                'masa_tunggu' => null,
                'tanggal_mulai_instansi' => null,
                'jenis_instansi' => null,
                'nama_instansi' => null,
                'skala_instansi' => null,
                'lokasi_instansi' => null,
                'kategori_profesi' => null,
                'profesi' => null,
                'nama_atasan' => null,
                'jabatan_atasan' => null,
                'no_hp_atasan' => null,
                'email_atasan' => null,
            ],
        ]);
    }
}